name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  test:
    
    runs-on: ubuntu-latest
    
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Create destinations
        run: ./gradlew kspDebugKotlin 
      
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        
      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: app/build/test-results/report.txt # path to where the xml test results are stored
        
  report:
    
    runs-on: ubuntu-latest
    
    needs: test
    if: ${{ always() }}
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v3
        with:
          name: reports
          path: app/build/test-results/report.txt
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
